=== pauloricardoferreira/odbc_oracle_client/stage/cvu/cv/cvdata/constraints.dtd
<!-- DTD for constraint model, used in CDM module, Cluster verification -->

<!--
*  
* RootConstraint:
*   As the name indicates, it is the root constraint
*
* BranchConstraint:
*
* Constraint:
-->

<!-- Predefined types for Constraint, simple type.
     These are defined as entity so that the changes can be made at one place.
 -->
<!ENTITY % STypeEntity
 "(OS | OSVER | OSPATCH | KRNVER | KRNPARAM | SYSPARAM |
  PACKAGE | LIB | FILE | PATH | CLASSPATH | EXE | SPACE |
   REGENTRY | ALIVE | USER | GROUP | USERGRP | OWNERSHIP |
    PORT | JAVAVER | RAWSIZE | SWAP | FREEMEM | TOTALMEM  |
     NUMPROCESSOR | OCRVER | ARCHITECTURE )" >

<!-- Qualifiers to be used in Constraint.  
-->
<!ENTITY % SQualifierEntity 
  "(LT | LTE | GT | GTE | EXIST | NOTEXIST | EQUAL | 
    NOTEQUAL | ALIVE | NOTALIVE | DISCOVER | COMPARE | QUERY )" >

<!-- Action on failure entity -->
<!ENTITY % FallbackEntity "( STOP | WARN | INFO | SKIP )" >

<!-- Leaf level building block.
-->
<!ELEMENT Constraint ( KeyData, RefData ) >

<!ATTLIST Constraint Type %STypeEntity; #REQUIRED >
<!ATTLIST Constraint FallbackAction %FallbackEntity; #IMPLIED >
<!ATTLIST Constraint Qualifier %SQualifierEntity; #REQUIRED >
<!ATTLIST Constraint Condition CDATA #IMPLIED >

<!-- NOTE: These child elements could have been defined as attributes of 
     Constraint. There is a fair chance that these will 
     become more complicated to address issues like indirection and 
     reference. Modelling them as child element provides better flexibility
     in this direction.  
-->
<!ELEMENT KeyData (#PCDATA) >
<!ELEMENT RefData (#PCDATA) >

<!-- BranchConstraint
-->
<!ELEMENT BranchConstraint ( Constraint+ ) >

<!ATTLIST BranchConstraint Name CDATA #REQUIRED >

<!-- RootConstraint 
-->
<!ELEMENT RootConstraint ( BranchConstraint+ ) >

=== pauloricardoferreira/odbc_oracle_client/stage/cvu/cv/cvdata/constraints.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE RootConstraint SYSTEM "constraints.dtd" >

<!-- DO NOT MODIFY THIS FILE -->
<RootConstraint>


  <!-- for Windows 2003 DATABASE  -->
  <BranchConstraint Name="SystemRequirement_db_5.2" >

    <!-- OS version check -->
    <Constraint Type="OSVER"
                FallbackAction="SKIP"
		Qualifier="EQUAL" >
      <RefData>Windows Server 2003</RefData>
    </Constraint>

    <!-- service pack 2 or higher -->
    <Constraint Type="OSPATCH"
                FallbackAction="STOP"
		Qualifier="GTE" >
      <KeyData>2</KeyData>
    </Constraint>

    <!-- 512MB RAM -->
    <!-- Memory check -->
    <Constraint Type="TOTALMEM"
                FallbackAction="STOP"
		Qualifier="GTE" >
      <RefData>536870912</RefData>
    </Constraint>

    <!-- Swap check -->
    <Constraint Type="SWAP"
                FallbackAction="SKIP"
		Qualifier="GTE" >
      <RefData>1073741824</RefData>
    </Constraint>

    <!-- Architecture check -->
    <Constraint Type="ARCHITECTURE"
                FallbackAction="STOP"
		Qualifier="EQUAL" >
      <RefData>64-bit</RefData>
    </Constraint>

    <!-- Space check -->
    <Constraint Type="SPACE"
                FallbackAction="SKIP"
		Qualifier="GTE" >
      <KeyData>$CV_TMP</KeyData>
      <RefData>419430400</RefData>
    </Constraint>
  </BranchConstraint>
  <!-- end of SystemRequirement_db_5.2 branch -->

  <BranchConstraint Name="SystemRequirement_db_5.2_10gR2" >

    <!-- OS version check -->
    <Constraint Type="OSVER"
                FallbackAction="SKIP"
		Qualifier="EQUAL" >
      <RefData>Windows Server 2003</RefData>
    </Constraint>

    <!-- service pack 2 or higher -->
    <Constraint Type="OSPATCH"
                FallbackAction="STOP"
		Qualifier="GTE" >
      <KeyData>2</KeyData>
    </Constraint>

    <!-- 512MB RAM -->
    <!-- Memory check -->
    <Constraint Type="TOTALMEM"
                FallbackAction="STOP"
		Qualifier="GTE" >
      <RefData>536870912</RefData>
    </Constraint>

    <!-- Swap check -->
    <Constraint Type="SWAP"
                FallbackAction="SKIP"
		Qualifier="GTE" >
      <RefData>1073741824</RefData>
    </Constraint>

    <!-- Architecture check -->
    <Constraint Type="ARCHITECTURE"
                FallbackAction="STOP"
		Qualifier="EQUAL" >
      <RefData>64-bit</RefData>
    </Constraint>

    <!-- Space check -->
    <Constraint Type="SPACE"
                FallbackAction="SKIP"
		Qualifier="GTE" >
      <KeyData>$CV_TMP</KeyData>
      <RefData>419430400</RefData>
    </Constraint>
  </BranchConstraint>
  <!-- end of SystemRequirement_db_5.2_10gR2 branch -->

  <BranchConstraint Name="SystemRequirement_db_5.2_10gR1" >

    <!-- OS version check -->
    <Constraint Type="OSVER"
                FallbackAction="SKIP"
		Qualifier="EQUAL" >
      <RefData>Windows Server 2003</RefData>
    </Constraint>

    <!-- service pack 2 or higher -->
    <Constraint Type="OSPATCH"
                FallbackAction="STOP"
		Qualifier="GTE" >
      <KeyData>2</KeyData>
    </Constraint>

    <!-- 512MB RAM -->
    <!-- Memory check -->
    <Constraint Type="TOTALMEM"
                FallbackAction="STOP"
		Qualifier="GTE" >
      <RefData>536870912</RefData>
    </Constraint>

    <!-- Swap check -->
    <Constraint Type="SWAP"
                FallbackAction="SKIP"
		Qualifier="GTE" >
      <RefData>1073741824</RefData>
    </Constraint>

    <!-- Architecture check -->
    <Constraint Type="ARCHITECTURE"
                FallbackAction="STOP"
		Qualifier="EQUAL" >
      <RefData>64-bit</RefData>
    </Constraint>

    <!-- Space check -->
    <Constraint Type="SPACE"
                FallbackAction="SKIP"
		Qualifier="GTE" >
      <KeyData>$CV_TMP</KeyData>
      <RefData>419430400</RefData>
    </Constraint>
  </BranchConstraint>
  <!-- end of SystemRequirement_db_5.2_10gR1 branch -->

  <!-- for Windows 2003 CRS  -->
  <BranchConstraint Name="SystemRequirement_crs_5.2" >

    <!-- OS version check -->
    <Constraint Type="OSVER"
                FallbackAction="SKIP"
		Qualifier="EQUAL" >
      <RefData>Windows Server 2003</RefData>
    </Constraint>

    <!-- service pack 2 or higher -->
    <Constraint Type="OSPATCH"
                FallbackAction="STOP"
		Qualifier="GTE" >
      <KeyData>2</KeyData>
    </Constraint>

    <!-- 512MB RAM -->
    <!-- Memory check -->
    <Constraint Type="TOTALMEM"
                FallbackAction="STOP"
		Qualifier="GTE" >
      <RefData>536870912</RefData>
    </Constraint>

    <!-- Swap check -->
    <Constraint Type="SWAP"
                FallbackAction="SKIP"
		Qualifier="GTE" >
      <RefData>1073741824</RefData>
    </Constraint>

    <!-- Architecture check -->
    <Constraint Type="ARCHITECTURE"
                FallbackAction="STOP"
		Qualifier="EQUAL" >
      <RefData>64-bit</RefData>
    </Constraint>

    <!-- Space check -->
    <Constraint Type="SPACE"
                FallbackAction="SKIP"
		Qualifier="GTE" >
      <KeyData>$CV_TMP</KeyData>
      <RefData>419430400</RefData>
    </Constraint>
  </BranchConstraint>
  <!-- end of SystemRequirement_crs_5.2 branch -->

  <BranchConstraint Name="SystemRequirement_crs_5.2_10gR2" >

    <!-- OS version check -->
    <Constraint Type="OSVER"
                FallbackAction="SKIP"
		Qualifier="EQUAL" >
      <RefData>Windows Server 2003</RefData>
    </Constraint>

    <!-- service pack 2 or higher -->
    <Constraint Type="OSPATCH"
                FallbackAction="STOP"
		Qualifier="GTE" >
      <KeyData>2</KeyData>
    </Constraint>

    <!-- 512MB RAM -->
    <!-- Memory check -->
    <Constraint Type="TOTALMEM"
                FallbackAction="STOP"
		Qualifier="GTE" >
      <RefData>536870912</RefData>
    </Constraint>

    <!-- Swap check -->
    <Constraint Type="SWAP"
                FallbackAction="SKIP"
		Qualifier="GTE" >
      <RefData>1073741824</RefData>
    </Constraint>

    <!-- Architecture check -->
    <Constraint Type="ARCHITECTURE"
                FallbackAction="STOP"
		Qualifier="EQUAL" >
      <RefData>64-bit</RefData>
    </Constraint>

    <!-- Space check -->
    <Constraint Type="SPACE"
                FallbackAction="SKIP"
		Qualifier="GTE" >
      <KeyData>$CV_TMP</KeyData>
      <RefData>419430400</RefData>
    </Constraint>
  </BranchConstraint>
  <!-- end of SystemRequirement_crs_5.2_10gR2 branch -->

  <BranchConstraint Name="SystemRequirement_crs_5.2_10gR1" >

    <!-- OS version check -->
    <Constraint Type="OSVER"
                FallbackAction="SKIP"
		Qualifier="EQUAL" >
      <RefData>Windows Server 2003</RefData>
    </Constraint>

    <!-- service pack 2 or higher -->
    <Constraint Type="OSPATCH"
                FallbackAction="STOP"
		Qualifier="GTE" >
      <KeyData>2</KeyData>
    </Constraint>

    <!-- 512MB RAM -->
    <!-- Memory check -->
    <Constraint Type="TOTALMEM"
                FallbackAction="STOP"
		Qualifier="GTE" >
      <RefData>536870912</RefData>
    </Constraint>

    <!-- Swap check -->
    <Constraint Type="SWAP"
                FallbackAction="SKIP"
		Qualifier="GTE" >
      <RefData>1073741824</RefData>
    </Constraint>

    <!-- Architecture check -->
    <Constraint Type="ARCHITECTURE"
                FallbackAction="STOP"
		Qualifier="EQUAL" >
      <RefData>64-bit</RefData>
    </Constraint>

    <!-- Space check -->
    <Constraint Type="SPACE"
                FallbackAction="SKIP"
		Qualifier="GTE" >
      <KeyData>$CV_TMP</KeyData>
      <RefData>419430400</RefData>
    </Constraint>
  </BranchConstraint>
  <!-- end of SystemRequirement_crs_5.2_10gR1 branch -->

  <BranchConstraint Name="peer_compatibility_5.2" > 

    <!-- Memory check -->
    <Constraint Type="TOTALMEM"
                FallbackAction="SKIP"
		Qualifier="COMPARE" >
    </Constraint>

    <!-- Swap check -->
    <Constraint Type="SWAP"
                FallbackAction="SKIP"
		Qualifier="COMPARE" >
    </Constraint>

    <!-- Architecture check -->
    <Constraint Type="ARCHITECTURE"
                FallbackAction="SKIP"
		Qualifier="COMPARE" >
    </Constraint>

    <!-- OS version check -->
    <Constraint Type="OSVER"
                FallbackAction="SKIP"
		Qualifier="COMPARE" >
    </Constraint>

  </BranchConstraint>
  <!-- end of peer_compatibility_5.2 branch -->

  <BranchConstraint Name="peer_compatibility_5.2_10gR2" > 

    <!-- Memory check -->
    <Constraint Type="TOTALMEM"
                FallbackAction="SKIP"
		Qualifier="COMPARE" >
    </Constraint>

    <!-- Swap check -->
    <Constraint Type="SWAP"
                FallbackAction="SKIP"
		Qualifier="COMPARE" >
    </Constraint>

    <!-- Architecture check -->
    <Constraint Type="ARCHITECTURE"
                FallbackAction="SKIP"
		Qualifier="COMPARE" >
    </Constraint>

    <!-- OS version check -->
    <Constraint Type="OSVER"
                FallbackAction="SKIP"
		Qualifier="COMPARE" >
    </Constraint>

  </BranchConstraint>
  <!-- end of peer_compatibility_5.2_10gR2 branch -->

  <BranchConstraint Name="peer_compatibility_5.2_10gR1" > 

    <!-- Memory check -->
    <Constraint Type="TOTALMEM"
                FallbackAction="SKIP"
		Qualifier="COMPARE" >
    </Constraint>

    <!-- Swap check -->
    <Constraint Type="SWAP"
                FallbackAction="SKIP"
		Qualifier="COMPARE" >
    </Constraint>

    <!-- Architecture check -->
    <Constraint Type="ARCHITECTURE"
                FallbackAction="SKIP"
		Qualifier="COMPARE" >
    </Constraint>

    <!-- OS version check -->
    <Constraint Type="OSVER"
                FallbackAction="SKIP"
		Qualifier="COMPARE" >
    </Constraint>

  </BranchConstraint>
  <!-- end of peer_compatibility_5.2_10gR1 branch -->
  <!-- End of peer -->


  <!-- for Windows 2008 DATABASE  -->
  <BranchConstraint Name="SystemRequirement_db_6.0" >

    <!-- OS version check -->
    <Constraint Type="OSVER"
                FallbackAction="SKIP"
              Qualifier="EQUAL" >
      <RefData>Windows Server 2008</RefData>
    </Constraint>
